name: Test and Deploy

on: [push, pull_request]

env:
  DOCKER_USERNAME: tobiaszimmer

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup variables
        run: |
          version=1.0.0
          lower_case_image=$(echo $IMAGE_NAME | awk '{print tolower($0)}')
          echo "project_version=$version" >> $GITHUB_ENV
          echo "lower_case_image=$lower_case_image" >> $GITHUB_ENV
          echo "branch_name=$(echo $GITHUB_REF | cut -d'/' -f 3 | tr / -)" >> $GITHUB_ENV
        env:
          IMAGE_NAME: ${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}

      - name: Deploy services
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
          image="$lower_case_image:$branch_name-$project_version"
          cd Code
          docker build -f monolithic.Dockerfile --tag "$image" .
          docker push "$image"
          
          postgres_image="$lower_case_image:$branch_name-postgres"
          cd volumes
          docker build -f postgres.Dockerfile --tag "$postgres_image" .
          docker push "$postgres_image"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ env.lower_case_image }}
          provider: dockerhub
          short_description: "Awesome Microservice"
          readme_file: "DOCKER_README.md"

      - name: Push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: ${{ env.lower_case_image }}
          provider: dockerhub
          short_description: "Legacy monolithic food to go application"
          readme_file: "DOCKER_README.md"

